INSERT INTO "Users" (
    "EmployeeCode",
    "Email",
    "FullName",
    "PasswordHash",
    "PhoneNumber",
    "ProfileImageUrl",
    "Designation",
    "Department",
    "State",
    "LGA",
    "HealthFacility",
    "Project",
    "BankName",
    "AccountNumber",
    "AccountName",
    "NINName",
    "NINNumber",
    "TINName",
    "TINNumber",
    "EmergencyContactName",
    "EmergencyContactPhone",
    "ContractStatus",
    "ContractStartDate",
    "ContractEndDate",
    "RoleId",
    "IsActive",
    "CreatedAt",
    "FailedLoginAttempts"
) VALUES (
    'ECEWS/001/00001',
    'ecews.supervisor@atms.com',
    'Mike Bolaji',  -- ECEWS Supervisor
    'eTVv4gJ53rdH4g8ZkThWpw==.Y2hlY2ttYXRl',  -- 'Password123!' hashed
    '08012345679',
    NULL,
    'ECEWS Supervisor',
    'Supervision',
    'Lagos',
    'Ikeja',
    'General Hospital',
    'ACE5',
    'First Bank',
    '0123456790',
    'Mike Bolaji',
    'Mike Bolaji',
    '12345678902',
    'Mike Bolaji',
    '12345678-0002',
    'Sarah Bolaji',
    '08098765431',
    'Active',
    '2026-01-01',
    '2026-12-31',
    2,  -- RoleId for EcewsSupervisor
    true,
    NOW(),
    0
);