INSERT INTO "Users" (
    "EmployeeCode",
    "Email",
    "FullName",
    "PasswordHash",
    "PhoneNumber",
    "ProfileImageUrl",
    "Designation",
    "Department",
    "State",
    "LGA",
    "HealthFacility",
    "Project",
    "BankName",
    "AccountNumber",
    "AccountName",
    "NINName",
    "NINNumber",
    "TINName",
    "TINNumber",
    "EmergencyContactName",
    "EmergencyContactPhone",
    "ContractStatus",
    "ContractStartDate",
    "ContractEndDate",
    "RoleId",
    "IsActive",
    "CreatedAt",
    "FailedLoginAttempts"
) VALUES (
    'GON/001/00001',  -- EmployeeCode
    'gon.supervisor@atms.com',
    'Amina Mohammed',  -- GON Supervisor
    'eTVv4gJ53rdH4g8ZkThWpw==.Y2hlY2ttYXRl',  -- This is 'Password123!' hashed (you'll need proper hash)
    '08012345678',
    NULL,
    'GON Supervisor',
    'Supervision',
    'Abuja',
    'Municipal',
    'National Hospital',
    'ACE5',
    'First Bank',
    '0123456789',
    'Amina Mohammed',
    'Amina Mohammed',
    '12345678901',
    'Amina Mohammed',
    '12345678-0001',
    'Ibrahim Mohammed',
    '08098765432',
    'Active',
    '2026-01-01',
    '2026-12-31',
    3,  -- RoleId for GonSupervisor
    true,
    NOW(),
    0
);