select * from public."Users"
SELECT Id, FullName, "EmployeeCode" FROM public."Users" WHERE "RoleId" IN (2,3);

INSERT INTO "Users" (
    "EmployeeCode",
    "Email",
    "FullName",
    "PasswordHash",
    "PhoneNumber",
    "ProfileImageUrl",
    "Designation",
    "Department",
    "State",
    "LGA",
    "HealthFacility",
    "Project",
    "BankName",
    "AccountNumber",
    "AccountName",
    "NINName",
    "NINNumber",
    "TINName",
    "TINNumber",
    "EmergencyContactName",
    "EmergencyContactPhone",
    "ContractStatus",
    "ContractStartDate",
    "ContractEndDate",
    "RoleId",
    "EcewsSupervisorId",
    "GonSupervisorId",
    "IsActive",
    "CreatedAt",
    "FailedLoginAttempts"
) VALUES (
    'CRS/CAM/053',
    'ekpenigeria@gmail.com',
    'Isaac Junior',
    'eTVv4gJ53rdH4g8ZkThWpw==.Y2hlY2ttYXRl',  -- 'Password123!' hashed
    '08012345680',
    NULL,
    'DEC',
    'Monitoring & Evaluation',
    'Cross River',
    'Calabar Municipal',
    'UCTH',
    'ACE5',
    'First Bank',
    '0123456800',
    'Isaac Junior',
    'Isaac Junior',
    '12345678903',
    'Isaac Junior',
    '12345678-0003',
    'Favour Divine',
    '08098765430',
    'Active',
    '2026-01-01',
    '2026-12-31',
    1,  -- RoleId for AdHoc
    2,  -- EcewsSupervisorId (Mike Bolaji)
    1,  -- GonSupervisorId (Amina Mohammed)
    true,
    NOW(),
    0
);

INSERT INTO "Users" (
    "EmployeeCode",
    "Email",
    "FullName",
    "PasswordHash",
    "PhoneNumber",
    "ProfileImageUrl",
    "Designation",
    "Department",
    "State",
    "LGA",
    "HealthFacility",
    "Project",
    "BankName",
    "AccountNumber",
    "AccountName",
    "NINName",
    "NINNumber",
    "TINName",
    "TINNumber",
    "EmergencyContactName",
    "EmergencyContactPhone",
    "ContractStatus",
    "ContractStartDate",
    "ContractEndDate",
    "RoleId",
    "EcewsSupervisorId",
    "GonSupervisorId",
    "IsActive",
    "CreatedAt",
    "FailedLoginAttempts"
) VALUES (
    'LAG/IKE/00002',
    'sarah.okonjo@atms.com',
    'Sarah Okonjo',
    'eTVv4gJ53rdH4g8ZkThWpw==.Y2hlY2ttYXRl',  -- 'Password123!' hashed
    '08012345681',
    NULL,
    'Field Worker',
    'Field Operations',
    'Lagos',
    'Ikeja',
    'General Hospital',
    'ACE5',
    'Access Bank',
    '0123456801',
    'Sarah Okonjo',
    'Sarah Okonjo',
    '12345678904',
    'Sarah Okonjo',
    '12345678-0004',
    'Peter Okonjo',
    '08098765429',
    'Active',
    '2026-01-01',
    '2026-12-31',
    1,  -- RoleId for AdHoc
    2,  -- EcewsSupervisorId (Mike Bolaji)
    1,  -- GonSupervisorId (Amina Mohammed)
    true,
    NOW(),
    0
);